//! Modules lint rules for starlint.
//!
//! Provides [`create_plugin`] to construct a [`Plugin`] containing all
//! modules rules.

pub mod rules;

starlint_rule_framework::declare_plugin! {
    name: "modules",
    rules: [
        crate::rules::import::consistent_type_specifier_style::ConsistentTypeSpecifierStyle,
        crate::rules::import::default::DefaultExport,
        crate::rules::import::export::ExportRule,
        crate::rules::import::exports_last::ExportsLast,
        crate::rules::import::extensions::Extensions,
        crate::rules::import::first::First,
        crate::rules::import::group_exports::GroupExports,
        crate::rules::import::max_dependencies::MaxDependencies::new(),
        crate::rules::import::named::NamedExport,
        crate::rules::import::namespace::NamespaceImport,
        crate::rules::import::no_absolute_path::NoAbsolutePath,
        crate::rules::import::no_amd::NoAmd,
        crate::rules::import::no_anonymous_default_export::NoAnonymousDefaultExport,
        crate::rules::import::no_commonjs::NoCommonjs,
        crate::rules::import::no_cycle::NoCycle,
        crate::rules::import::no_default_export::NoDefaultExport,
        crate::rules::import::no_duplicates::NoDuplicates,
        crate::rules::import::no_dynamic_require::NoDynamicRequire,
        crate::rules::import::no_empty_named_blocks::NoEmptyNamedBlocks,
        crate::rules::import::no_mutable_exports::NoMutableExports,
        crate::rules::import::no_named_as_default::NoNamedAsDefault,
        crate::rules::import::no_named_as_default_member::NoNamedAsDefaultMember,
        crate::rules::import::no_named_default::NoNamedDefault,
        crate::rules::import::no_named_export::NoNamedExport,
        crate::rules::import::no_namespace::NoNamespace,
        crate::rules::import::no_nodejs_modules::NoNodejsModules,
        crate::rules::import::no_relative_parent_imports::NoRelativeParentImports,
        crate::rules::import::no_restricted_imports::NoRestrictedImports,
        crate::rules::import::no_self_import::NoSelfImport,
        crate::rules::import::no_unassigned_import::NoUnassignedImport,
        crate::rules::import::no_webpack_loader_syntax::NoWebpackLoaderSyntax,
        crate::rules::import::prefer_default_export::PreferDefaultExport,
        crate::rules::import::unambiguous::Unambiguous,
        crate::rules::node::global_require::GlobalRequire::new(),
        crate::rules::node::no_exports_assign::NoExportsAssign,
        crate::rules::node::no_new_require::NoNewRequire,
        crate::rules::node::no_path_concat::NoPathConcat,
        crate::rules::node::no_process_env::NoProcessEnv,
        crate::rules::node::no_process_exit::NoProcessExit,
        crate::rules::promise::always_return::AlwaysReturn,
        crate::rules::promise::avoid_new::AvoidNew,
        crate::rules::promise::catch_or_return::CatchOrReturn,
        crate::rules::promise::no_callback_in_promise::NoCallbackInPromise,
        crate::rules::promise::no_multiple_resolved::NoMultipleResolved,
        crate::rules::promise::no_native::NoNative,
        crate::rules::promise::no_nesting::NoNesting,
        crate::rules::promise::no_new_statics::NoNewStatics,
        crate::rules::promise::no_promise_in_callback::NoPromiseInCallback,
        crate::rules::promise::no_return_in_finally::NoReturnInFinally,
        crate::rules::promise::no_return_wrap::NoReturnWrap,
        crate::rules::promise::param_names::ParamNames,
        crate::rules::promise::prefer_await_to_callbacks::PreferAwaitToCallbacks,
        crate::rules::promise::prefer_await_to_then::PreferAwaitToThen,
        crate::rules::promise::spec_only::SpecOnly,
        crate::rules::promise::valid_params::ValidParams,
    ]
}
