//! Lint rules using the unified [`LintRule`] trait.
//!
//! These rules use [`AstTree`] instead of oxc's `AstKind`. As rules are
//! migrated from `NativeRule` to `LintRule`, they move here.

pub mod eqeqeq;
pub mod no_debugger;
pub mod no_empty;
pub mod no_var;

use crate::lint_rule::LintRule;

/// Return all unified [`LintRule`] implementations.
#[must_use]
pub fn all_lint_rules() -> Vec<Box<dyn LintRule>> {
    use crate::rules;

    vec![
        // POC rules (Phase 2)
        Box::new(eqeqeq::Eqeqeq),
        Box::new(no_debugger::NoDebugger),
        Box::new(no_empty::NoEmpty),
        Box::new(no_var::NoVar),
        // Migrated rules (Phase 4)
        Box::new(rules::approx_constant::ApproxConstant),
        Box::new(rules::bad_bitwise_operator::BadBitwiseOperator),
        Box::new(rules::bad_char_at_comparison::BadCharAtComparison),
        Box::new(rules::bad_comparison_sequence::BadComparisonSequence),
        Box::new(rules::bad_replace_all_arg::BadReplaceAllArg),
        Box::new(rules::consistent_empty_array_spread::ConsistentEmptyArraySpread),
        Box::new(rules::double_comparisons::DoubleComparisons),
        Box::new(rules::empty_brace_spaces::EmptyBraceSpaces),
        Box::new(rules::erasing_op::ErasingOp),
        Box::new(rules::error_message::ErrorMessage),
        Box::new(rules::escape_case::EscapeCase),
        Box::new(rules::func_names::FuncNames),
        Box::new(rules::func_style::FuncStyle),
        Box::new(rules::id_length::IdLength::new()),
        Box::new(rules::jest::no_conditional_in_test::NoConditionalInTest),
        Box::new(rules::jest::no_test_return_statement::NoTestReturnStatement),
        Box::new(rules::nextjs::google_font_display::GoogleFontDisplay),
        Box::new(rules::no_alert::NoAlert),
        Box::new(rules::no_array_constructor::NoArrayConstructor),
        Box::new(rules::no_bitwise::NoBitwise),
        Box::new(rules::no_caller::NoCaller),
        Box::new(rules::no_compare_neg_zero::NoCompareNegZero),
        Box::new(rules::no_const_enum::NoConstEnum),
        Box::new(rules::no_continue::NoContinue),
        Box::new(rules::no_delete_var::NoDeleteVar),
        Box::new(rules::no_div_regex::NoDivRegex),
        Box::new(rules::no_document_cookie::NoDocumentCookie),
        Box::new(rules::no_empty_character_class::NoEmptyCharacterClass),
        Box::new(rules::no_empty_function::NoEmptyFunction),
        Box::new(rules::no_empty_pattern::NoEmptyPattern),
        Box::new(rules::no_empty_static_block::NoEmptyStaticBlock),
        Box::new(rules::no_eq_null::NoEqNull),
        Box::new(rules::no_extra_boolean_cast::NoExtraBooleanCast),
        Box::new(rules::no_extra_semi::NoExtraSemi),
        Box::new(rules::no_hex_escape::NoHexEscape),
        Box::new(rules::no_iterator::NoIterator),
        Box::new(rules::no_keyword_prefix::NoKeywordPrefix),
        Box::new(rules::no_label_var::NoLabelVar),
        Box::new(rules::no_labels::NoLabels),
        Box::new(rules::no_multi_assign::NoMultiAssign),
        Box::new(rules::no_multi_str::NoMultiStr),
        Box::new(rules::no_nested_ternary::NoNestedTernary),
        Box::new(rules::no_new::NoNew),
        Box::new(rules::no_new_func::NoNewFunc),
        Box::new(rules::no_new_wrappers::NoNewWrappers),
        Box::new(rules::no_nonoctal_decimal_escape::NoNonoctalDecimalEscape),
        Box::new(rules::no_null::NoNull),
        Box::new(rules::no_optional_chaining::NoOptionalChaining),
        Box::new(rules::no_plusplus::NoPlusplus),
        Box::new(rules::no_process_exit::NoProcessExit),
        Box::new(rules::no_proto::NoProto),
        Box::new(rules::no_restricted_globals::NoRestrictedGlobals::new()),
        Box::new(rules::no_script_url::NoScriptUrl),
        Box::new(rules::no_shadow_restricted_names::NoShadowRestrictedNames),
        Box::new(rules::no_template_curly_in_string::NoTemplateCurlyInString),
        Box::new(rules::no_ternary::NoTernary),
        Box::new(rules::no_this_assignment::NoThisAssignment),
        Box::new(rules::no_throw_literal::NoThrowLiteral),
        Box::new(rules::no_undefined::NoUndefined),
        Box::new(rules::no_useless_concat::NoUselessConcat),
        Box::new(rules::no_useless_escape::NoUselessEscape),
        Box::new(rules::no_void::NoVoid),
        Box::new(rules::no_with::NoWith),
        Box::new(rules::no_zero_fractions::NoZeroFractions),
        Box::new(rules::number_literal_case::NumberLiteralCase),
        Box::new(rules::numeric_separators_style::NumericSeparatorsStyle),
        Box::new(rules::prefer_global_this::PreferGlobalThis),
        Box::new(rules::prefer_rest_params::PreferRestParams),
        Box::new(rules::promise::no_native::NoNative),
        Box::new(rules::symbol_description::SymbolDescription),
        Box::new(rules::text_encoding_identifier_case::TextEncodingIdentifierCase),
        Box::new(rules::unicode_bom::UnicodeBom),
        Box::new(rules::use_isnan::UseIsnan),
        Box::new(rules::valid_typeof::ValidTypeof),
    ]
}

/// Names of rules that have been migrated to [`LintRule`].
///
/// These must be excluded from the native rule set to avoid duplicate diagnostics.
pub const MIGRATED_RULE_NAMES: &[&str] = &[
    "eqeqeq",
    "no-debugger",
    "no-empty",
    "no-var",
    // Phase 4 migrated rules
    "approx-constant",
    "bad-bitwise-operator",
    "bad-char-at-comparison",
    "bad-comparison-sequence",
    "bad-replace-all-arg",
    "consistent-empty-array-spread",
    "double-comparisons",
    "empty-brace-spaces",
    "erasing-op",
    "error-message",
    "escape-case",
    "func-names",
    "func-style",
    "id-length",
    "jest/no-conditional-in-test",
    "jest/no-test-return-statement",
    "nextjs/google-font-display",
    "no-alert",
    "no-array-constructor",
    "no-bitwise",
    "no-caller",
    "no-compare-neg-zero",
    "no-const-enum",
    "no-continue",
    "no-delete-var",
    "no-div-regex",
    "no-document-cookie",
    "no-empty-character-class",
    "no-empty-function",
    "no-empty-pattern",
    "no-empty-static-block",
    "no-eq-null",
    "no-extra-boolean-cast",
    "no-extra-semi",
    "no-hex-escape",
    "no-iterator",
    "no-keyword-prefix",
    "no-label-var",
    "no-labels",
    "no-multi-assign",
    "no-multi-str",
    "no-nested-ternary",
    "no-new",
    "no-new-func",
    "no-new-wrappers",
    "no-nonoctal-decimal-escape",
    "no-null",
    "no-optional-chaining",
    "no-plusplus",
    "no-process-exit",
    "no-proto",
    "no-restricted-globals",
    "no-script-url",
    "no-shadow-restricted-names",
    "no-template-curly-in-string",
    "no-ternary",
    "no-this-assignment",
    "no-throw-literal",
    "no-undefined",
    "no-useless-concat",
    "no-useless-escape",
    "no-void",
    "no-with",
    "no-zero-fractions",
    "number-literal-case",
    "numeric-separators-style",
    "prefer-global-this",
    "prefer-rest-params",
    "promise/no-native",
    "symbol-description",
    "text-encoding-identifier-case",
    "unicode-bom",
    "use-isnan",
    "valid-typeof",
];
